# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  paths:
    include:
      - apis/trips

pool:
  vmImage: ubuntu-latest

steps:
- script: which go
- task: GoTool@0

- script: 
    which go
    pwd
    ls /opt/hostedtoolcache/go/

- task: Go@0
  inputs:
    command: 'get'
    workingDirectory: '/apis/trips/'

- task: Go@0
  inputs:
    command: 'test'
    workingDirectory: '/apis/trips/tests'
    arguments: -v 