# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  paths:
    include:
    - 'apis/trips/*'
    - 'cicd/trips-build-test-pipeline.yml'
    
  pr:
    branches:
      include:
      - main
    paths:
      include:
      - 'apis/trips/*'
      - 'cicd/trips-build-test-pipeline.yml'
      
pool:
  vmImage: ubuntu-latest
steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'azureOpenHackRegistryServiceConnection1'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'azureOpenHackRegistryServiceConnection1'
      repository: 'devopsoh/api-trips'
      command: 'buildAndPush'
      Dockerfile: 'apis/trips/Dockerfile'
