# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
    - 'apis/user-java/*'

pr:
  branches:
    include:
    - main
  paths:
    include:
    - 'apis/user-java/*'
    - 'cicd/user-java-build-test-pipeline.yml'

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'azureOpenHackRegistryServiceConnection1'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'azureOpenHackRegistryServiceConnection1'
    repository: 'devopsoh/api-user-java'
    command: 'buildAndPush'
    Dockerfile: 'apis/user-java/Dockerfile'