# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'apis/userprofile/*'
    - 'cicd/userprofile-build-test-pipeline.yml'
    - polling.sh

pr:
  branches:
    include:
    - main
  paths:
    include:
    - 'apis/userprofile/*'
    - 'cicd/userprofile-build-test-pipeline.yml'
    - polling.sh

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build User Profile
  jobs:
    - job: Userprofile
      displayName: Build User profile
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'apis/userprofile'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'apis/userprofile'
          customCommand: 'run test'
      - task: Docker@2
        condition: and(succeeded(), eq(variables.isMain, 'true'))
        inputs:
          containerRegistry: 'azureOpenHackRegistryServiceConnection1'
          command: 'login'

      - task: Docker@2
        condition: and(succeeded(), eq(variables.isMain, 'true'))
        inputs:
          containerRegistry: 'azureOpenHackRegistryServiceConnection1'
          repository: 'devopsoh/api-userprofile'
          command: 'buildAndPush'
          Dockerfile: 'apis/userprofile/Dockerfile'

    - job: ErrorHandler
      dependsOn: Userprofile
      condition: failed()
      steps: 
      - bash: |
          az boards work-item create \
            --title "Build $(build.buildNumber) failed" \
            --type issue \
            --org $(System.TeamFoundationCollectionUri) \
            --project $(System.TeamProject)
        env: 
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        displayName: 'Create work item on failure'   

- stage:
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Deploy App to Staging
  jobs:
  - job: Staging
    displayName: Deploy User profile on Stage
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'appServiceSubsciptionConnection'
        appType: 'webAppContainer'
        WebAppName: 'openhackxhg88362userprofile'
        deployToSlotOrASE: true
        ResourceGroupName: 'openhackxhg88362rg'
        SlotName: 'staging'
        DockerNamespace: 'openhackxhg88362acr.azurecr.io'
        DockerRepository: 'devopsoh/api-userprofile'
        DockerImageTag: '$(Build.BuildId)'
  
  - job: HealthCheckStaging
    dependsOn: Staging
    displayName: Health Check on Staging
    steps: 
    - task: Bash@3
      inputs:
        filePath: 'polling.sh'
        arguments: 'https://openhackxhg88362userprofile-staging.azurewebsites.net/api/healthcheck/user'


- stage:
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Deploy App on Prod
  jobs:
  - job: Prod
    displayName: Deploy User profile on Prod
    steps:
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'appServiceSubsciptionConnection'
        Action: 'Swap Slots'
        WebAppName: 'openhackxhg88362userprofile'
        ResourceGroupName: 'openhackxhg88362rg'
        SourceSlot: 'staging'

  - job: HealthCheckProd
    dependsOn: Prod
    displayName: Health Check on Prod
    steps: 
    - task: Bash@3
      inputs:
        filePath: 'polling.sh'
        arguments: 'https://openhackxhg88362userprofile.azurewebsites.net/api/healthcheck/user'
    - task: AzureAppServiceManage@0
      condition: failed()
      inputs:
        azureSubscription: 'appServiceSubsciptionConnection'
        Action: 'Swap Slots'
        WebAppName: 'openhackxhg88362userprofile'
        ResourceGroupName: 'openhackxhg88362rg'
        SourceSlot: 'staging'
        
