# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'apis/userprofile/*'
    
pr:
  branches:
    include:
    - main
  paths:
    include:
    - 'apis/userprofile/*'
    - 'cicd/userprofile-build-test-pipeline.yml'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build User Profile
  jobs:
    - job: Userprofile
      displayName: Build User profile
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'apis/userprofile'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'apis/userprofile'
          customCommand: 'run test'
      - task: Docker@2
        inputs:
          containerRegistry: 'azureOpenHackRegistryServiceConnection1'
          command: 'login'

      - task: Docker@2
        inputs:
          containerRegistry: 'azureOpenHackRegistryServiceConnection1'
          repository: 'devopsoh/api-userprofile'
          command: 'buildAndPush'
          Dockerfile: 'apis/userprofile/Dockerfile'

    - job: ErrorHandler
      dependsOn: Userprofile
      condition: failed()
      steps: 
      - bash: |
          az boards work-item create \
            --title "Build $(build.buildNumber) failed" \
            --type issue \
            --org $(System.TeamFoundationCollectionUri) \
            --project $(System.TeamProject)
        env: 
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        displayName: 'Create work item on failure'   
